on: push

name: Build and deploy Node app to AWS EBS 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:    

    #checkout and Zip
    - uses: actions/checkout@master
    - run: |
        git archive -v -o NodeExpressSampleApp.1.zip --format=zip HEAD
        pwd
        ls
    #copy files to s3 bucket
    - uses: actions/aws/cli@master 
      with:
        args: s3 cp NodeExpressSampleApp.1.zip s3://elasticbeanstalk-us-east-2-653237029202/ 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    
    #create application
    - uses: actions/aws/cli@master 
      with:
        args: elasticbeanstalk create-application-version --application-name Node_demo --version-label v0.1 --description NodeAppv1 --source-bundle S3Bucket="elasticbeanstalk-us-east-2-653237029202",S3Key="NodeExpressSampleApp.1.zip"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    #deploy elasticbeanstalk
    - uses: actions/aws/cli@master 
      with:
        args: elasticbeanstalk update-environment --application-name Node_demo --environment-name NodeDemo-env --version-label v0.1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
